export class ReportType{
    static WH_GENERIC = "WH_GENERIC"
    static FS_GENERIC = "FS_GENERIC"

    static WH_INVENTARISATION = "WH_INVENTARISATION"
    static WH_RELEASE = "WH_RELEASE"
    static WH_REPLENISHMENT = "WH_REPLENISHMENT"
    static WH_WS_REPLENISHMENT = "WH_WS_REPLENISHMENT"
    static WH_SHIPMENT = "WH_SHIPMENT"

    static FS_SUP_REQ = "FS_SUP_REQ"
    static FS_WORKSHIFT = "FS_WORKSHIFT"

}


export class ReportFieldType {
  static NOT_ACCESSIBLE = 'NOT_ACCESSIBLE';
  static STRING = 'STRING';
  static DELETED_DATETIME = 'DELETED_DATETIME';
  static DATETIME = 'DATETIME';
  static WAREHOUSE_SELECT = 'WAREHOUSE_SELECT';
  static SUP_REQ_REP_SELECT = 'SUP_REQ_REP_SELECT';
  static WS_REP_SELECT = 'WS_REP_SELECT';
  static ITEMS_LIST = 'ITEMS_LIST';
  static PRODUCTS_LIST = 'PRODUCTS_LIST';
  static ITEMS_LIST_VARIANTS = 'ITEMS_LIST_VARIANTS';
  static PRODUCTS_LIST_VARIANTS = 'PRODUCTS_LIST_VARIANTS';
}
